# Site settings
title: Hugo Júnior
description: 'Página para publicação de artigos aleátorios sobre assuntos aleátorios.'
url: 'http://blog.hugojunior.com'
baseurl: '/'
google_analytics: 'UA-69336887-3'
disqus_shortname: 'hugojuniior'

author:
  name: 'Hugo Júnior'
  email: contato@hugojunior.com
  twitter_username: hugojuniior
  facebook_username: hugojuniior
  github_username:  hugojunior
  linkedin_username:  hugojunior

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:categories/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
