#-------------------------------
# General Site Settings
title: Hugo Júnior - Explorando o Mundo Tecnológico
logo: logo.png
description: Um cearense entusiasta de tecnologia, estudante, desenvolvedor e gamer, estou sempre explorando este vasto universo de zeros e uns.
url: "https://hugojunior.com"
preview: preview.png


#-------------------------------
# Author Settings
author:
  name: Hugo Júnior
  image: banner-home.jpg
  say-hello: Olá! Sou <strong><a>Hugo Júnior</a></strong>,
  bio: Um cearense entusiasta de <strong>tecnologia</strong>, estudante, desenvolvedor e gamer, estou sempre explorando este vasto universo de zeros e uns.


#-------------------------------
# Contact links
github: https://github.com/hugojunior
linkedin: https://linkedin.com/in/hugojunior
twitter: https://twitter.com/hugojuniior
instagram: https://instagram.com/hugojunior
email: contato@hugojunior.com


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: hugojuniior


#-------------------------------
# Google Analytics
google-analytics: G-WMBHW3QS2C
